### ISSUE TITLE
IDE Fatal error when opening large JSP file

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javaee#32]
I'm constantly seing same IDE Fatal Error appearing and appearing again. I think it's related to large JSP file. Though I may be wrong. But error itself doesn't say much about file or place in this file it was caused by. I think you at least must add more details into its message saying what part of source code does it dislike so much.

It says:
`PsiLiteralExpression:')'.isValidHost() in class com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl returned false so you mustn't inject here.: PsiLiteralExpression:')'.isValidHost() in class com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl returned false so you mustn't inject here.`

Stacktrace:
```
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.addPlace(InjectionRegistrarImpl.java:136)
	at org.intellij.plugins.intelliLang.inject.InjectorUtils.registerInjection(InjectorUtils.java:126)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector$3.processInjection(ConcatenationInjector.java:151)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector$InjectionProcessor.processInjectionWithContext(ConcatenationInjector.java:448)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector$InjectionProcessor.processXmlInjections(ConcatenationInjector.java:368)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector$InjectionProcessor.process(ConcatenationInjector.java:328)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector$InjectionProcessor.access$400(ConcatenationInjector.java:178)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector$InjectionProcessor$1.visitMethodParameter(ConcatenationInjector.java:228)
	at org.intellij.plugins.intelliLang.util.AnnotationUtilEx.visitAnnotatedElementInner(AnnotationUtilEx.java:174)
	at org.intellij.plugins.intelliLang.util.AnnotationUtilEx.visitAnnotatedElements(AnnotationUtilEx.java:132)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector$InjectionProcessor.processInjections(ConcatenationInjector.java:304)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector.inject(ConcatenationInjector.java:174)
	at com.intellij.psi.impl.source.tree.injected.ConcatenationInjectorManager.doCompute(ConcatenationInjectorManager.java:54)
	at com.intellij.psi.impl.source.tree.injected.ConcatenationInjectorManager.access$300(ConcatenationInjectorManager.java:28)
	at com.intellij.psi.impl.source.tree.injected.ConcatenationInjectorManager$BaseConcatenation2InjectorAdapter.injectLanguages(ConcatenationInjectorManager.java:97)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:374)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.probeElementsUp(InjectedLanguageUtil.java:336)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:166)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.enumerateEx(InjectedLanguageManagerImpl.java:273)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$getInjectedPsiFiles$3(InjectedGeneralHighlightingPass.java:174)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:135)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:233)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:160)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:233)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:160)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:233)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:160)
	at consulo.application.impl.BaseApplication.tryRunReadAction(BaseApplication.java:534)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:592)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:539)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:180)
	at consulo.application.impl.BaseApplication.executeByImpatientReader(BaseApplication.java:588)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)



java.lang.IllegalArgumentException: PsiLiteralExpression:')'.isValidHost() in class com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl returned false so you mustn't inject here.
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.addPlace(InjectionRegistrarImpl.java:136)
	at org.intellij.plugins.intelliLang.inject.InjectorUtils.registerInjection(InjectorUtils.java:126)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector$3.processInjection(ConcatenationInjector.java:151)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector$InjectionProcessor.processInjectionWithContext(ConcatenationInjector.java:448)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector$InjectionProcessor.processXmlInjections(ConcatenationInjector.java:368)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector$InjectionProcessor.process(ConcatenationInjector.java:328)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector$InjectionProcessor.access$400(ConcatenationInjector.java:178)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector$InjectionProcessor$1.visitMethodParameter(ConcatenationInjector.java:228)
	at org.intellij.plugins.intelliLang.util.AnnotationUtilEx.visitAnnotatedElementInner(AnnotationUtilEx.java:174)
	at org.intellij.plugins.intelliLang.util.AnnotationUtilEx.visitAnnotatedElements(AnnotationUtilEx.java:132)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector$InjectionProcessor.processInjections(ConcatenationInjector.java:304)
	at org.intellij.plugins.intelliLang.inject.java.ConcatenationInjector.inject(ConcatenationInjector.java:174)
	at com.intellij.psi.impl.source.tree.injected.ConcatenationInjectorManager.doCompute(ConcatenationInjectorManager.java:54)
	at com.intellij.psi.impl.source.tree.injected.ConcatenationInjectorManager.access$300(ConcatenationInjectorManager.java:28)
	at com.intellij.psi.impl.source.tree.injected.ConcatenationInjectorManager$BaseConcatenation2InjectorAdapter.injectLanguages(ConcatenationInjectorManager.java:97)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:374)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.probeElementsUp(InjectedLanguageUtil.java:336)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:166)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.enumerateEx(InjectedLanguageManagerImpl.java:273)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$getInjectedPsiFiles$3(InjectedGeneralHighlightingPass.java:174)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:135)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:233)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:160)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:233)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:160)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:233)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:160)
	at consulo.application.impl.BaseApplication.tryRunReadAction(BaseApplication.java:534)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:592)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:539)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:180)
	at consulo.application.impl.BaseApplication.executeByImpatientReader(BaseApplication.java:588)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by VISTALL** [comment]
fixed
